"""Tables for Scrapping and Processing

Revision ID: 2193a3487a6c
Revises: 4328869eb72e
Create Date: 2025-10-12 13:39:29.379565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2193a3487a6c'
down_revision: Union[str, Sequence[str], None] = '4328869eb72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_raw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fetch_uri', sa.String(length=1000), nullable=False),
    sa.Column('structure', sa.String(), nullable=False),
    sa.Column('delimiter', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_raw_fetch_uri'), 'metadata_raw', ['fetch_uri'], unique=True)
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('pdf_uri', sa.String(length=1000), nullable=False),
    sa.Column('pdf_raw', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata_raw.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_documents_metadata_id'), 'raw_documents', ['metadata_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_documents_metadata_id'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_metadata_raw_fetch_uri'), table_name='metadata_raw')
    op.drop_table('metadata_raw')
    # ### end Alembic commands ###
