"""Changed Structure Field to Json

Revision ID: 529156b8c6e0
Revises: c6f25c10e6cf
Create Date: 2025-10-12 15:10:53.684826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529156b8c6e0'
down_revision: Union[str, Sequence[str], None] = 'c6f25c10e6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metadata_raw', 'structure',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='structure::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metadata_raw', 'structure',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='structure::text')
    # ### end Alembic commands ###
