"""Base Document Strucuture

Revision ID: 8e4afd34c833
Revises: 
Create Date: 2026-02-08 00:43:52.060291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e4afd34c833'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('jurisdiction', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('raw_content_uri', sa.Text(), nullable=True),
    sa.Column('legal_status', sa.String(length=255), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('advocates', sa.Text(), nullable=True),
    sa.Column('case_type', sa.Text(), nullable=True),
    sa.Column('case_number', sa.Text(), nullable=True),
    sa.Column('bench', sa.Text(), nullable=True),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_doc_type'), 'case_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_case_documents_jurisdiction'), 'case_documents', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_case_documents_reference_id'), 'case_documents', ['reference_id'], unique=True)
    op.create_index(op.f('ix_case_documents_source'), 'case_documents', ['source'], unique=False)
    op.create_index(op.f('ix_case_documents_year'), 'case_documents', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_documents_year'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_source'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_reference_id'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_jurisdiction'), table_name='case_documents')
    op.drop_index(op.f('ix_case_documents_doc_type'), table_name='case_documents')
    op.drop_table('case_documents')
    # ### end Alembic commands ###
