"""Alter the Structure Field in Metadata Raw

Revision ID: c6f25c10e6cf
Revises: d33a03a144a3
Create Date: 2025-10-12 15:06:08.970788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f25c10e6cf'
down_revision: Union[str, Sequence[str], None] = 'd33a03a144a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
