"""Added Raw Content Field in Documents Table

Revision ID: d33a03a144a3
Revises: 2193a3487a6c
Create Date: 2025-10-12 14:33:50.774945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33a03a144a3'
down_revision: Union[str, Sequence[str], None] = '2193a3487a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('raw_content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'raw_content')
    # ### end Alembic commands ###
