"""Changed the Date Column to Year

Revision ID: f2dc07e875bd
Revises: 529156b8c6e0
Create Date: 2025-10-12 23:18:43.934293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2dc07e875bd'
down_revision: Union[str, Sequence[str], None] = '529156b8c6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('year', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.drop_column('documents', 'date')
    op.add_column('metadata_chunks', sa.Column('year', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_metadata_chunks_year'), 'metadata_chunks', ['year'], unique=False)
    op.drop_column('metadata_chunks', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadata_chunks', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_metadata_chunks_year'), table_name='metadata_chunks')
    op.drop_column('metadata_chunks', 'year')
    op.add_column('documents', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_column('documents', 'year')
    # ### end Alembic commands ###
